### ISSUE TITLE
Paypal Express IPN

### ISSUE THREAD

**Issue by toddvalentine** [silverstripe/silverstripe-omnipay#156]
I just recently have started getting an error where incorrect TransactionReference is getting set on my Payments. I don't have apache access data back far enough to know if anything has changed on the Paypal end, but the initial IPN response from Paypal is 

"GET /paymentendpoint/bac5ad69c59d319a7172bd4935ab5c/complete?token=EC-XXXXXXXXX&PayerID=XXXXXXXXX HTTP/1.1" 302

milliseconds later I get the following

"POST /paymentendpoint/bac5ad69c59d319a7172bd4935ab5c/notify HTTP/1.1" 200 5690 "-" "PayPal IPN ( https://www.paypal.com/ipn )"

The token in the initial GET request is being set as the TransactionReference on my Payment. So when I attempt to Refund, I get an error.

If I manually update the TransactionReference to the correct one pulled from the IPN request in Paypal and try to Refund I am successful.

Everything was working as recently as 12/4.

**Comment by bummzack** [comment]
What version of omnipay and silverstripe-omnipay are you using?

**Comment by toddvalentine** [comment]
"silverstripe/silverstripe-omnipay": "^2.0"

which requires:

"omnipay/common": "~2.4"

**Comment by bummzack** [comment]
What version of the paypal gateway are you using? eg. omnipay/paypal? Does upgrading to the latest version help?

**Comment by toddvalentine** [comment]
silverstripe/omnipay requires ~2.5, so my composer.lock file is showing v2.6.2 which is the most up to date stable version.

**Comment by bummzack** [comment]
Have you figured out, where things go wrong, eg. which line of code? Is it only when attempting a refund?

**Comment by toddvalentine** [comment]
Things go wrong when the GET request is made and omnipay grabs the token value in the request and sets it as the TransactionReference. Funds are successfully captured, but refunds cannot be made since the Payment has an incorrect reference to the Paypal TransactionID. Very strange that this just started happening. TransactionReference values were getting set correctly as recently as 12/4.

**Comment by bummzack** [comment]
Can you reproduce this issue with the PayPal Sandbox? I just gave it a try and refunds seem to be working fine.

**Comment by toddvalentine** [comment]
Yeah, reproduced on sandbox. Still grabbing the token from the complete status request and using it as TransactionReference. Possibly on a side note, is there a way to disable the module from attempting to write to debug.log? I have tried everything in my config and can't disable, so I get alot of errors. My current config is below:

```
Payment:
  allowed_gateways:
    - 'PayPal_Express'
  file_logging: false

GatewayInfo:
  PayPal_Express:
    parameters:
      username: ‘XXXXXXXX’
      password: '1234567’
      signature: ‘XXXXXXXX’
---
Except:
  environment: 'live'
---
GatewayInfo:
  PayPal_Express:
    parameters:
      testMode: true
---
Only:
  environment: 'live'
---
GatewayInfo:
  PayPal_Express:
    parameters:
      username: ‘XXXXXXXX’
      password: ‘1234567’
      testMode: false
      signature: ‘XXXXXXX’
```
