### ISSUE TITLE
Add Identifier, and/or TransactionReference to summary_fields

### ISSUE THREAD

**Issue by jedateach** [silverstripe/silverstripe-omnipay#169]
To diagnose a 'Pending purchase' payment that had actually succeeded on the gateway, I had to add the 'Identifier' field to my summary fields.

I actually also re-ordered the fields to look like this:
```yaml
    summary_fields:
        Created.Nice: Created
        Money: Money
        Identifier: Reference
        GatewayTitle: Gateway
        PaymentStatus: Status
```

I initially assumed that 'TransactionReference' was what I wanted to expose in the CMS UI, but it turned out to be 'Identifier'. So the above config is confusing from a development perspective. It should make sense to a CMS user though.

So therefore, I think we should update code commenting to clarify why we have Identifier and TransactionReference (in addition to the Payment's ID). Possibly even renaming one/both of these?
