### ISSUE TITLE
Store sensitive info such as GatewayInfo user and pass in .env, not YML

### ISSUE THREAD

**Issue by Leapfrognz** [silverstripe/silverstripe-omnipay#209]
Potential security issue, storing GatewayInfo in yml means the values are committed into code.
These should be set in .env, or at least provide the option of using .env rather than yml.
Bad:
```
SilverStripe\Omnipay\GatewayInfo:
  PaymentExpress_PxPay:
    parameters:
      username: 'imausername'
      password: 'myinsecurepassword'
```

**Comment by sanderha** [comment]
+1 on this. Any news? :-)

**Comment by mlewis-everley** [comment]
I have thought about this a bit recently as well, the problem (as far as I can see) is finding a way to standardize the format of the variables in .env (as omnipay gateways could potentially use any key value pairs to hold this data).

I guess as an idea off the top of my head, you could set this module to look to a common env variable format and then write something to convert those environmental variables to config? Maybe something like:

`OMNIPAY__PaymentExpress_PxPay__username=someusername`

@bummzack, @wilr Any thoughts on this?

**Comment by bummzack** [comment]
I never commit my `payment.yml` file… so it's about as safe as using a `.env` file for these config variables.

But if you think this gives a lot of extra security, please feel free to PR that feature. I'd rather not use a different config format in the `.env` file though. Since SilverStripe already has a [format for placeholders in YML](https://docs.silverstripe.org/en/4/developer_guides/extending/injector/) (scroll down to *Using constants as variables*), I'd just go ahead and use that format (sadly it's not possible to use that feature directly, since placeholders are only substituted in injector calls). So your config would look something like:

```yaml
SilverStripe\Omnipay\GatewayInfo:
  PaymentExpress_PxPay:
    parameters:
      username: '`PXPAY_USERNAME`'
      password: '`PXPAY_PASSWORD`'
```

Then you'd have the following environment variables (either in `.env` or real env-vars):
```
PXPAY_USERNAME="imausername"
PXPAY_PASSWORD="myinsecurepassword"
```
