### ISSUE TITLE
is this the way to do the Paypal Test Payment and how do I know it is a test and not a real payment

### ISSUE THREAD

**Issue by sunnysideup** [silverstripe/silverstripe-omnipay#25]
Hi Jeremy

I have the following code:

``` php



    function PaymentForm(){
        if($this->showPaymentForm) {
            $gateway = "PayPal_Express";
            $factory = new GatewayFieldsFactory($gateway);
            $fields = $factory->getFields();
            $actions = new FieldList(new FormAction("pay", "Pay Now"));
            return new Form($this, "PaymentForm", $fields, $actions);
        }
    }

    function pay($form, $data) {
        $isTestMode = Director::IsLive() ? false : true;
        if($amount = $this->result->AmountToPay()) {
            $currency = $this->result->CurrencyToPay();
            $payment = Payment::create()
                ->init($gateway = "PayPal_Express", $amount, $currency)
                ->setReturnUrl($this->Link('completepayment'))
                ->setCancelUrl($this->Link('cancelpayment'));  //$form->getData()
            Session::set("OmniPayPaymentID", $payment->ID);
          $payment->oGateway()->setTestMode($isTestMode);
            $purchase = $payment->purchase();
            $purchase->redirect();
        }
    }


    function completepayment($request){
        $id = Session::get("OmniPayPaymentID");
        Session::clear("OmniPayPaymentID");
        $payment = Payment::get()->byID($id);
        $payment->Status = "Authorized";
        $payment->write();
        return $this->redirect($this->Link());  }

    function cancelpayment($request){
        $id = Session::get("OmniPayPaymentID");
        Session::clear("OmniPayPaymentID");
        $payment = Payment::get()->byID($id);
        $payment->Status = "Void";
        $payment->write();
        return $this->redirect($this->Link());
    }

```

and in yml:

``` yml

---
Name: payment

---
Payment:
  has_one:
    QuestionnaireResult: QuestionnaireResult
  allowed_gateways:
    - 'PayPal_Express'
    - 'Manual'
  parameters:
    PayPal_Express:
      username: 'pay_api1.sunnysideup.co.nz'
      password: 'real password'
      signature: 'real signature'

---
Only:
    environment: 'live'

---
Payment:
    parameters:
        PayPal_Express:
            username: 'liveexample.test'
            password: 'livepassawe23'
            signature: 'laivfe23235235'

```

This seems to work ok, except that I dont think it is in test mode...

I am not sure where I can find more information about this or how to fix his.

Ideally I could also write $payment->IsTestMode(true) rather than the construction above...

ALSO -  the way I process the payments (cancel and success) is DEFINITELY wrong (you can just browse to the URLs to make a payment!) ... How do you envisage this to work?

Cheers

Nicolaas
